swagger: "2.0"
info:
  title: Food Ordering System API
  description: API for placing food orders and displaying queue numbers
  version: 1.0.0
schemes:
  - https
paths:
  /order:
    post:
      summary: Place a new order
      parameters:
        - name: order
          in: body
          required: true
          schema:
            $ref: "#/definitions/OrderRequest"
      responses:
        "200":
          description: Order placed successfully
          schema:
            $ref: "#/definitions/OrderResponse"
        "400":
          description: Invalid input
  /queue-numbers:
    get:
      summary: Get a list of queue numbers with different statuses
      responses:
        "200":
          description: Successful response
          schema:
            $ref: "#/definitions/QueueStatus"
definitions:
  OrderRequest:
    type: object
    properties:
      items:
        type: array
        items:
          $ref: "#/definitions/OrderItem"
      checkboxDeclare:
        type: boolean
    required:
      - items
      - checkboxDeclare
    example:
      items:
        - itemName: Bee hoon
          quantity: 2
        - itemName: Uncle Roger's fried rice
          quantity: 1
      checkboxDeclare: true
  OrderItem:
    type: object
    properties:
      itemName:
        type: string
      quantity:
        type: integer
    required:
      - itemName
      - quantity
  OrderResponse:
    type: object
    properties:
      queueNum:
        type: integer
  QueueStatus:
    type: object
    properties:
      collection:
        type: integer
      preparing:
        type: array
        items:
          type: integer
